#!/usr/bin/env bash

# Remember the current directory
CURRENT_DIR=$(pwd)

# Change directory so we can search only within our notes
cd $HOME/Main/neorg/notes/

# Search with preview and open in nvim
nvim $(fzf --style=full --reverse --preview="bat --color=always {}")

# Move back to previous directory
cd $CURRENT_DIR
