#!/usr/bin/env bash

# Script to copy passwords from pass using rofi

available_passwords=$(cd $HOME/.password-store && find . -type f -not -path '*/\.git/*')

# We need to remove the path and file extension
filtered_passwords=$(echo "$available_passwords" | sed 's|^\./||; s|\.[^.]*$||')

selection=$(echo "$filtered_passwords" | rofi -dmenu -p "Select password to copy:")

if [[ $selection != "" ]]; then
		pass -c $selection && notify-send "Copied $selection to clipboard"
fi
