#!/usr/bin/env bash

SHADER="$HOME/.config/hypr/shaders/grayscale.glsl"
PREVIOUS_BRIGHTNESS="/tmp/previous-brightness"

# Check active shader

if hyprshade current | grep -q "grayscale"; then

    hyprshade off
    hyprctl reload

    # Check if previous brightness file exists
    if [[ -f $PREVIOUS_BRIGHTNESS ]]; then
        brightnessctl set "$(cat $PREVIOUS_BRIGHTNESS)%"
    else
        brightnessctl set 60%
    fi
    waybar &


else

    # Record previous brightness
    echo "$(python -c "print(int(100 * $(brightnessctl g) / $(brightnessctl m)))")" > $PREVIOUS_BRIGHTNESS

    hyprshade on $SHADER
    pkill waybar

    brightnessctl set 37%

    # Force E-ink visuals: No animations, no shadows, thin black borders
    hyprctl keyword animations:enabled 0
    hyprctl keyword decoration:drop_shadow 0
    hyprctl keyword decoration:blur:enabled 0
    hyprctl keyword decoration:rounding 0
    hyprctl keyword general:gaps_in 0
    hyprctl keyword general:gaps_out 0
    hyprctl keyword general:border_size 2
    hyprctl keyword general:col.active_border "rgba(000000ff)"
    hyprctl keyword general:col.inactive_border "rgba(000000ff)"
    hyprctl keyword decoration:dim_inactive 0

fi
