#!/usr/bin/env bash

WALLPAPER_DIRECTORY=$HOME/Photos/Wallpapers/

# Selec wallpaper from above directory
# Mark selection with 'm'
CHOICE=$(nsxiv -otb $WALLPAPER_DIRECTORY)

# Generate colours
if [ "$1" = "-l" ]; then
	echo "GENERATING LIGHT THEME!"
	wal --backend haishoku -i "$CHOICE" -l --cols16 -n

else
	echo "GENERATING DARK THEME!"
	wal --backend haishoku -i "$CHOICE" --cols16 -n
fi

hyprctl hyprpaper reload ,"$CHOICE"

# Waybar needs to be refreshed to change colours
killall waybar; waybar

# Set mozilla stuff
pywalfox update
