#!/usr/bin/env bash

WALLPAPER="~/Photos/Wallpapers/_current_wallpaper"

killall waybar

# Generate colors and set wallpaper with wal
wal --theme "base16-gruvbox-hard" --cols16 -i $WALLPAPER
#
# Wait for pywal to finish fully
while [ ! -f "${HOME}/.cache/wal/colors-waybar.css" ]; do
    sleep 0.1
done

# Start hyprpaper
hyprpaper &

# Wait a bit to ensure hyprpaper starts and wal finishes
sleep 1

# Apply the wallpaper using hyprctl
hyprctl hyprpaper wallpaper ,"$WALLPAPER"
waybar &
