# Profile will run at login

# Directory Clean Up
export ZDOTDIR="$HOME/.config/zsh"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export QMK_HOME="/home/daraghhollman/Main/qmk_firmware/"
