# ----------------  Path Config -------------------- #

path=(
    $path
    $HOME/Copernicus/scripts/
    $HOME/Main/notes/scripts/
    $HOME/Main/expenses/scripts/
)

# Remove any duplicates
typeset -U path
path=($^path(N-/))

export PATH

# ----------------- Zsh Options -------------------- #

set -o vi

# Enable Colours
autoload -U colors && colors
#
# Enable history and place in cache
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history
setopt INC_APPEND_HISTORY # All shell sessions append to history after exiting
setopt HIST_IGNORE_DUPS # Consecutive repeated lines are ignored

# Edit command in vim buffer
autoload edit-command-line; zle -N edit-command-line
bindkey "^e" edit-command-line

# ------------ Environement Variables -------------- #

export EDITOR=nvim
export BROWSER=qutebrowser

export NOTESDIR="$HOME/Main/notes/"
export EXPENSES_DIR="$HOME/Main/expenses/"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket

# ------------------- Plugins ---------------------- #

# Tab comletions
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # Include dot files

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

(cat ~/.cache/wal/sequences &) # Colours from wal

# Search history with ctrl-r
source /usr/share/zsh/plugins/zsh-fzf-history-search/zsh-fzf-history-search.zsh

# Auto suggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Add syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ------------------ Aliases --------------------- #

alias open="xdg-open"
# Setting defaults for opening
xdg-mime default swayimg.desktop image/jpeg
xdg-mime default swayimg.desktop image/png
xdg-mime default org.pwmt.zathura.desktop application/pdf
# More to be added as we come across them

alias grep='grep --color=auto'

alias ls="exa"

alias ..='cd ..'
alias ...='cd ..; cd ..'
alias ....='cd ..; cd ..; cd ..'
alias .....='cd ..; cd ..; cd ..; cd ..;'

alias gst='git status'
alias ta='task add'

alias kepler_backup="rsync -a --delete --info=progress2 -v --exclude '~/.local/share/Trash/' --exclude '.cache/' --exclude '.config/Slack/' --exclude '.local/share/recently-used.xbel' -e 'ssh -p 22001' /home/daraghhollman/ daraghhollman@79.97.106.33:/storage/kepler_backup/"

alias hss='hugo server --noHTTPCache'
alias hsd='hugo server -D'

alias diasvpn="sudo openvpn --config /home/daraghhollman/Main/Work/vpn/dhollman.ovpn"

# Download from youtube
alias yt='yt-dlp --add-metadata -i'
alias yta='yt -x -f bestaudio/best'
alias ytp='yt --yes-playlist -x --audio-format best --audio-quality 0 --embed-metadata --embed-thumbnail --output "%(playlist_index)02d - %(title)s.%(ext)s"'

# Supress warnings
export PYTHONWARNINGS=ignore
# Papis helper functions
kpapis() {
	papis $@
	exit
}
bibexport() {
	papis export --format bibtex $1 | wl-copy
}
library_backup() {
	papis git add .
	papis git commit -m "Automated library backup $(date)"
	papis git push
}

# Yazi moves directory
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
zle -N y
bindkey "^o" y

# Defer pyenv init until needed
pyenv() {
	eval "$(command pyenv init - zsh)"
	eval "$(command pyenv virtualenv-init - zsh)"

	pyenv "$@"
}

alias fk="fuck"
eval "$(thefuck --alias)"

# Set prompt
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

# SSH AGENT
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [ ! -f "$SSH_AUTH_SOCK" ]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi
